  
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8.10
  pre_build:
    commands:
    - npm install --no-progress --silent
  build:
    commands:
    - npm start
    - npm test
    - serverless deploy
  